# Generated by Django 5.0.6 on 2024-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='tipo',
            field=models.CharField(choices=[('estaduais', 'Estaduais'), ('nacionais', 'Nacionais')], default='estaduais', max_length=10),
        ),
    ]
