# Generated by Django 5.0.6 on 2024-05-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0004_alter_jogo_data_alter_jogo_gols_time_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='rodada',
            field=models.IntegerField(default=1),
        ),
    ]
